// <auto-generated />
using BackendSecurite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendSecurite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726231225_AddRoleToUtilisateur")]
    partial class AddRoleToUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendSecurite.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrixApres")
                        .HasColumnType("float");

                    b.Property<double>("PrixAvant")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Take up to 18 months to pay with as low as 0% APR on some term lengths and no late fees",
                            Image = "assets/images/P2.jpg",
                            PrixApres = 349.0,
                            PrixAvant = 450.99000000000001,
                            Quantite = 7,
                            Titre = "Pack Sécurité ULTRA",
                            Type = "pack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vidéo 2K avancée avec multiples options d'alimentation.",
                            Image = "assets/images/C3.jpg",
                            PrixApres = 119.98999999999999,
                            PrixAvant = 0.0,
                            Quantite = 5,
                            Titre = "CAMERA HD HIKVISION",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sound the alarm, notify loved ones, and request emergency help when you need it with Alarm Panic Button. You can press and hold the Panic Button for three seconds to sound the siren on your Ring Alarm.",
                            Image = "assets/images/A2.jpg",
                            PrixApres = 39.990000000000002,
                            PrixAvant = 0.0,
                            Quantite = 12,
                            Titre = "Panic Button",
                            Type = "alarm"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vidéo 2K avancée avec multiples options d'alimentation.",
                            Image = "assets/images/C6.jpg",
                            PrixApres = 109.98999999999999,
                            PrixAvant = 0.0,
                            Quantite = 6,
                            Titre = "CAMERA UNIARCH IP",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Caméra Bullet UNIARCH IP 2MP IR30 Audio UV-IPC-B122-AFP28(40) - Surveillance Extérieure Haute Performance Solution professionnelle pour une protection 24h/24 des espaces extérieurs Son design bullet et sa technologie IR30m en font un choix idéal pour les parkings, entrepôts et périmètres sécurisés.",
                            Image = "assets/images/C1.jpg",
                            PrixApres = 89.989999999999995,
                            PrixAvant = 0.0,
                            Quantite = 10,
                            Titre = "Outdoor Cam",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Enjoy four battery-powered Pathlights that shine light on walkways, driveways and pathways when motion is detected. Connect Pathlights to the included Ring Bridge to enable smart controls in the Ring App and sync with other Ring Smart Lights",
                            Image = "assets/images/P4.jpg",
                            PrixApres = 280.0,
                            PrixAvant = 500.99000000000001,
                            Quantite = 4,
                            Titre = "Pack 8 caméras de surveillance 5MP D-LINK",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pack de 2 caméras pour une sécurité renforcée.",
                            Image = "assets/images/C2.jpg",
                            PrixApres = 139.0,
                            PrixAvant = 159.97999999999999,
                            Quantite = 9,
                            Titre = "CAMERA BULLET UNIARCH",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Take up to 18 months to pay with as low as 0% APR on some term lengths and no late fees",
                            Image = "assets/images/P1.jpg",
                            PrixApres = 129.0,
                            PrixAvant = 0.0,
                            Quantite = 4,
                            Titre = "Pack Floodlight Cam Pro",
                            Type = "pack"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Take up to 18 months to pay with as low as 0% APR on some term lengths and no late fees",
                            Image = "assets/images/A3.jpg",
                            PrixApres = 39.0,
                            PrixAvant = 0.0,
                            Quantite = 6,
                            Titre = "Alarm Window and Door Contact Sensor",
                            Type = "pack"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Enjoy four battery-powered Pathlights that shine light on walkways, driveways and pathways when motion is detected. Connect Pathlights to the included Ring Bridge to enable smart controls in the Ring App and sync with other Ring Smart Lights",
                            Image = "assets/images/P3.jpg",
                            PrixApres = 369.0,
                            PrixAvant = 450.99000000000001,
                            Quantite = 6,
                            Titre = "Pathlight 4-Pack + Bridge",
                            Type = "pack"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Vidéo 2K avancée avec multiples options d'alimentation.",
                            Image = "assets/images/C5.jpg",
                            PrixApres = 109.0,
                            PrixAvant = 0.0,
                            Quantite = 7,
                            Titre = "Smart Hybrid Light Camera",
                            Type = "camera"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The central core of your reliable Ring Alarm protection. Its armed with a powerful siren, plus built-in backups to help keep you secure for up to 24 hours if you lose power or internet.1Add Ring Alarm Sensors.",
                            Image = "assets/images/A1.jpg",
                            PrixApres = 269.99000000000001,
                            PrixAvant = 0.0,
                            Quantite = 9,
                            Titre = "Alarm Base Station",
                            Type = "alarm"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Take up to 18 months to pay with as low as 0% APR on some term lengths and no late fees",
                            Image = "assets/images/A4.jpg",
                            PrixApres = 65.0,
                            PrixAvant = 0.0,
                            Quantite = 3,
                            Titre = "DÉCLENCHEUR MANUEL",
                            Type = "alarm"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Vidéo 2K avancée avec multiples options d'alimentation.",
                            Image = "assets/images/C4.jpg",
                            PrixApres = 119.98999999999999,
                            PrixAvant = 0.0,
                            Quantite = 5,
                            Titre = "CAMÉRA PTZ DAHUA 2MP",
                            Type = "camera"
                        });
                });

            modelBuilder.Entity("BackendSecurite.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urgence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("ServiceRequest", b =>
                {
                    b.HasOne("BackendSecurite.Models.Utilisateur", "Utilisateur")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendSecurite.Models.Utilisateur", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
